name: flexivideoplayer
description: Video player with support of brightness, volume, back from full screen,full screen playing
version: 0.1.1

homepage: https://github.com/Dharini17/flexivideoplayer

environment:
  sdk: '>=2.12.0 <=3.7.3'
  flutter: "3.0.3"#">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  video_player: ^2.8.2
  wakelock: ^0.6.2
  volume_controller: ^2.0.7
  screen_brightness: ^1.0.0

dev_dependencies:
  lint: ^1.8.2
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
